/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 2ndyrGroupA
 */

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        
        display();
     
       
       
      
        DefaultTableCellRenderer rendar = new DefaultTableCellRenderer();
    
    tableuser.getColumnModel().getColumn(0).setCellRenderer(rendar); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        stocks = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        admin = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        adminuser = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        calculateproducts = new javax.swing.JLabel();
        calculateadmin = new javax.swing.JLabel();
        calculateuser = new javax.swing.JLabel();
        calculatedisabledadmin = new javax.swing.JLabel();
        calculateproductarchived = new javax.swing.JLabel();
        calculatesales = new javax.swing.JLabel();
        calculatedisabledusers = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        calculateorders = new javax.swing.JLabel();
        calculatestocks = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        stocks1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableproducts = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabledisabledusers = new javax.swing.JTable();
        unblockedusers = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabledisabledadmins = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        unblockedusers1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablearchivedproducts = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableuser = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableadmin = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableorders = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton3.setText("REFRESH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        stocks.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));
        stocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stocksActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Stocks");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(231, 76, 60));

        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        admin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminKeyPressed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminuser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminuser.setText("jLabel9");
        jPanel1.add(adminuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 86, 34));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("STOCKS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setText("TOTAL SALES");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 90, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("PRODUCTS");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 70, 20));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ADMIN");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("USER");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PRODUCT ARCHIVED");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 160, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DISABLED ADMINS");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DISABLED USERS");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, -1));

        calculateproducts.setBackground(new java.awt.Color(204, 51, 0));
        calculateproducts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculateproducts.setForeground(new java.awt.Color(255, 255, 255));
        calculateproducts.setText("jLabel17");
        jPanel1.add(calculateproducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        calculateadmin.setBackground(new java.awt.Color(204, 51, 0));
        calculateadmin.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        calculateadmin.setText("jLabel17");
        jPanel1.add(calculateadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        calculateuser.setBackground(new java.awt.Color(204, 51, 0));
        calculateuser.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        calculateuser.setText("jLabel17");
        jPanel1.add(calculateuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        calculatedisabledadmin.setBackground(new java.awt.Color(204, 51, 0));
        calculatedisabledadmin.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        calculatedisabledadmin.setText("jLabel17");
        jPanel1.add(calculatedisabledadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        calculateproductarchived.setBackground(new java.awt.Color(204, 51, 0));
        calculateproductarchived.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        calculateproductarchived.setText("jLabel17");
        jPanel1.add(calculateproductarchived, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        calculatesales.setBackground(new java.awt.Color(204, 51, 0));
        calculatesales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculatesales.setForeground(new java.awt.Color(255, 255, 255));
        calculatesales.setText("jLabel17");
        jPanel1.add(calculatesales, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        calculatedisabledusers.setBackground(new java.awt.Color(204, 51, 0));
        calculatedisabledusers.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        calculatedisabledusers.setText("jLabel17");
        jPanel1.add(calculatedisabledusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, -1, -1));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel27.setText("TOTAL ORDERS");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 120, 20));

        calculateorders.setBackground(new java.awt.Color(204, 51, 0));
        calculateorders.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        calculateorders.setForeground(new java.awt.Color(255, 255, 255));
        calculateorders.setText("jLabel17");
        jPanel1.add(calculateorders, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        calculatestocks.setBackground(new java.awt.Color(204, 51, 0));
        calculatestocks.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        calculatestocks.setText("jLabel17");
        jPanel1.add(calculatestocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homebackgroundz.png"))); // NOI18N
        jLabel30.setText("jLabel30");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 880, 510));

        admin.addTab("HOME", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("REFRESH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, -1, -1));

        jLabel3.setText("Name");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        name.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel4.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 162, 30));

        jLabel4.setText("Brand");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, -1, -1));

        brand.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));
        brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandActionPerformed(evt);
            }
        });
        jPanel4.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 161, 30));

        jLabel5.setText("Price");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 40, -1));

        price.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel4.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 160, 30));

        stocks1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), null));
        stocks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stocks1ActionPerformed(evt);
            }
        });
        jPanel4.add(stocks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 162, 30));

        jLabel7.setText("Stocks");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, -1, -1));

        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });
        jPanel4.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 160, 40));

        jLabel8.setText("Description");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, 20));

        tableproducts.setBackground(new java.awt.Color(255, 173, 12));
        tableproducts.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 86, 222), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 164, 28), new java.awt.Color(149, 162, 247)));
        tableproducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "name", "brand", "price", "stocks", "description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableproducts.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tableproducts.setGridColor(new java.awt.Color(204, 0, 51));
        tableproducts.setSelectionForeground(new java.awt.Color(255, 102, 0));
        jScrollPane6.setViewportView(tableproducts);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 470, 270));

        jButton5.setText("CRUD");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton12.setText("ADD");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/products.png"))); // NOI18N
        jLabel26.setText("jLabel26");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        admin.addTab("PRODUCTS", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabledisabledusers.setBackground(new java.awt.Color(255, 173, 12));
        tabledisabledusers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 86, 222), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 164, 28), new java.awt.Color(149, 162, 247)));
        tabledisabledusers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Email", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabledisabledusers.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tabledisabledusers.setGridColor(new java.awt.Color(204, 0, 51));
        tabledisabledusers.setSelectionForeground(new java.awt.Color(255, 102, 0));
        jScrollPane3.setViewportView(tabledisabledusers);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 580, 330));

        unblockedusers.setText("UNBLOCKED USERS");
        unblockedusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unblockedusersActionPerformed(evt);
            }
        });
        jPanel5.add(unblockedusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        jButton11.setText("REFRESH");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disabledusers.png"))); // NOI18N
        jLabel25.setText("jLabel25");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        admin.addTab("DISABLED USERS", jPanel5);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabledisabledadmins.setBackground(new java.awt.Color(255, 173, 12));
        tabledisabledadmins.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 86, 222), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 164, 28), new java.awt.Color(149, 162, 247)));
        tabledisabledadmins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Email", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabledisabledadmins.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tabledisabledadmins.setGridColor(new java.awt.Color(204, 0, 51));
        tabledisabledadmins.setSelectionForeground(new java.awt.Color(255, 102, 0));
        jScrollPane5.setViewportView(tabledisabledadmins);

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 620, 290));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DISABLED ADMINS");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        unblockedusers1.setText("ENABLE ADMIN");
        unblockedusers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unblockedusers1ActionPerformed(evt);
            }
        });
        jPanel7.add(unblockedusers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jButton9.setText("REFRESH");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disabledadmin.png"))); // NOI18N
        jLabel24.setText("jLabel24");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        admin.addTab("DISABLED ADMIN", jPanel7);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablearchivedproducts.setBackground(new java.awt.Color(255, 173, 12));
        tablearchivedproducts.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 86, 222), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 164, 28), new java.awt.Color(149, 162, 247)));
        tablearchivedproducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "name", "brand", "price", "stocks", "description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablearchivedproducts.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tablearchivedproducts.setGridColor(new java.awt.Color(204, 0, 51));
        tablearchivedproducts.setSelectionForeground(new java.awt.Color(255, 102, 0));
        jScrollPane7.setViewportView(tablearchivedproducts);

        jPanel9.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 420, 240));

        jButton6.setText("UNARCHIVE PRODUCT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jButton10.setText("REFRESH");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/archived.png"))); // NOI18N
        jLabel23.setText("jLabel23");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 510));

        admin.addTab("ARCHIVED PRODUCTS", jPanel9);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableuser.setBackground(new java.awt.Color(255, 173, 12));
        tableuser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 86, 222), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 164, 28), new java.awt.Color(149, 162, 247)));
        tableuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Email", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableuser.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tableuser.setGridColor(new java.awt.Color(204, 0, 51));
        tableuser.setSelectionForeground(new java.awt.Color(255, 102, 0));
        tableuser.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tableuserComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(tableuser);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 540, 280));

        jButton1.setText("ACTION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jButton7.setText("REFRESH");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jLabel22.setText("jLabel22");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        int count = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `tableuser` WHERE `status`= 'able' and `type`= 'user'");
            DefaultTableModel model = (DefaultTableModel) tableuser.getModel();
            while (datas.next()) {
                count = 1;
                model.addRow(new Object[]{datas.getInt("userId"),datas.getString("username"), datas.getString("email"), datas.getString("password")});
            }

            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        admin.addTab("USERS", jPanel2);

        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableadmin.setBackground(new java.awt.Color(255, 173, 12));
        tableadmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 86, 222), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 164, 28), new java.awt.Color(149, 162, 247)));
        tableadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Email", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableadmin.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tableadmin.setGridColor(new java.awt.Color(204, 0, 51));
        tableadmin.setSelectionForeground(new java.awt.Color(255, 102, 0));
        jScrollPane4.setViewportView(tableadmin);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 520, 220));

        jButton2.setText("ACTION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText(" ADMIN");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jButton8.setText("REFRESH");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        admin.addTab("ADMIN", jPanel3);

        tableorders.setBackground(new java.awt.Color(255, 173, 12));
        tableorders.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 86, 222), new java.awt.Color(0, 0, 0), new java.awt.Color(255, 164, 28), new java.awt.Color(149, 162, 247)));
        tableorders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "name", "brand", "price", "description", "quantity", "TotalPrice", "status", "Customer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableorders.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tableorders.setGridColor(new java.awt.Color(204, 0, 51));
        tableorders.setSelectionForeground(new java.awt.Color(255, 102, 0));
        jScrollPane8.setViewportView(tableorders);

        jButton13.setText("REFRESH");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton15.setText("Approved");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Cancel");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jButton15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton16))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addGap(49, 49, 49))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jButton15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        admin.addTab("ORDERS", jPanel13);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String[] crud = { "BLOCK","ADD USER","MAKE AS ADMIN"};
        int option = JOptionPane.showOptionDialog(null, "PROCEED ON", "PROCEED", 0, JOptionPane.QUESTION_MESSAGE, null, crud, "");

        if (crud[option] == "BLOCK") {

            new BLOCKUSER().setVisible(true);
         

        }
        else if (crud[option] == "ADD USER") {

            new ADDUSER().setVisible(true);
        

        }
        else if (crud[option] == "MAKE AS ADMIN") {

            new MAKEADMIN().setVisible(true);
        

        }
        else {

            JOptionPane.showMessageDialog(this, "OK OK !");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void unblockedusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unblockedusersActionPerformed
        // TODO add your handling code here:

        new UNBLOCKUSER().setVisible(true);
     

    }//GEN-LAST:event_unblockedusersActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String[] crud = { "DISABLE","EXIT"};
        int option = JOptionPane.showOptionDialog(null, "PROCEED ON", "PROCEED", 0, JOptionPane.QUESTION_MESSAGE, null, crud, "");

        if (crud[option] == "DISABLE") {

            new DISABLEADMIN().setVisible(true);
  

        }
        else if (crud[option] == "EXIT") {

            new dashboard().setVisible(true);
     

        }
        else {

            JOptionPane.showMessageDialog(this, "OK OK !");

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void unblockedusers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unblockedusers1ActionPerformed
        // TODO add your handling code here:

        new ENABLEADMIN().setVisible(true);
    
    }//GEN-LAST:event_unblockedusers1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
   
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new dashboard().setVisible(true);

        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void stocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stocksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stocksActionPerformed

    private void stocks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stocks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stocks1ActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_descriptionActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        String[] crud = { "UPDATE", "DELETE", "ARCHIVE","ORDER"};
        int option = JOptionPane.showOptionDialog(null, "PROCEED ON", "PROCEED", 0, JOptionPane.QUESTION_MESSAGE, null, crud, "");

        if (crud[option] == "UPDATE") {
            new UPDATE().setVisible(true);

        } else if (crud[option] == "DELETE") {
            new DELETE().setVisible(true);

        }
        else if (crud[option] == "ARCHIVE") {
            new ARCHIVEPRODUCT().setVisible(true);

        }
        
        else if (crud[option] == "ORDER") {
            new ORDERPRODUCT().setVisible(true);

        }

        else {

            JOptionPane.showMessageDialog(this, "OK OK !");

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new UNARCHIVEPRODUCTS().setVisible(true);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        // TODO add your handling code here:
       
      
        
        
    }//GEN-LAST:event_adminMouseClicked

    private void adminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_adminKeyPressed

    private void tableuserComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tableuserComponentShown
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_tableuserComponentShown

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown


        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jPanel3ComponentShown

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new dashboard().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.setVisible(false);
        new dashboard().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

      this.setVisible(false);
        new dashboard().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       
         this.setVisible(false);
        new dashboard().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        

        // TODO add your handling code here:
        this.setVisible(false);
        new dashboard().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        
       try {
            
        String pname = name.getText();
        String pbrand = brand.getText();     
        int pprice = Integer.parseInt(price.getText());
        int pstocks = Integer.parseInt(stocks1.getText());
        String pdescription = description.getText();
   
            
            Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
            String query = "INSERT INTO `products` (`productName`, `productBrand`,`productPrice`, `productStocks`, `productDescription`) VALUES ('" + pname + "','" + pbrand + "','" + pprice + "','" + pstocks + "','" + pdescription + "' )";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Product Added!");

            // ALERT ON DESTINATION RETRIEVE, UPDATE, DELETE,      
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       
        // TODO add your handling code here:
        
        this.setVisible(false);
        new dashboard().setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        
        new approvedorder().setVisible(true);
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
         new cancelorder().setVisible(true);
      
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new dashboard().setVisible(false);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane admin;
    public javax.swing.JLabel adminuser;
    private javax.swing.JTextField brand;
    public javax.swing.JLabel calculateadmin;
    public javax.swing.JLabel calculatedisabledadmin;
    public javax.swing.JLabel calculatedisabledusers;
    public javax.swing.JLabel calculateorders;
    public javax.swing.JLabel calculateproductarchived;
    public javax.swing.JLabel calculateproducts;
    public javax.swing.JLabel calculatesales;
    public javax.swing.JLabel calculatestocks;
    public javax.swing.JLabel calculateuser;
    private javax.swing.JTextField description;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField stocks;
    private javax.swing.JTextField stocks1;
    private javax.swing.JTable tableadmin;
    private javax.swing.JTable tablearchivedproducts;
    private javax.swing.JTable tabledisabledadmins;
    private javax.swing.JTable tabledisabledusers;
    public javax.swing.JTable tableorders;
    private javax.swing.JTable tableproducts;
    private javax.swing.JTable tableuser;
    private javax.swing.JButton unblockedusers;
    private javax.swing.JButton unblockedusers1;
    // End of variables declaration//GEN-END:variables

 
   public void display() {
        int count = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `users` WHERE `status`= 'able' and `type`= 'user'");
            DefaultTableModel model = (DefaultTableModel) tableuser.getModel();
            while (datas.next()) {
                count = 1;
                model.addRow(new Object[]{datas.getInt("userId"),datas.getString("username"), datas.getString("email"), datas.getString("password")});
            }
            
           
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
        
        
        /// DISPlAY ALL THE ADMIN
        
          int countz = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `users` WHERE `status`= 'able' and `type`= 'admin'");
            DefaultTableModel model = (DefaultTableModel) tableadmin.getModel();
 
            while (datas.next()) {
             
                countz = 1;
                model.addRow(new Object[]{datas.getInt("userId"),datas.getString("username"), datas.getString("email"), datas.getString("password")});
            }
       
         
           
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
        
        //DISPLAY PRODUCTS UNARCHIVED
        
            int countprod = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `products` WHERE `status`='unarchive'");
            DefaultTableModel model = (DefaultTableModel) tableproducts.getModel();
            while (datas.next()) {
                countprod = 1;
                model.addRow(new Object[]{datas.getInt("productId"),datas.getString("productName"), datas.getString("productBrand"), datas.getInt("productPrice"), datas.getInt("productStocks"), datas.getString("productDescription")});
            }
            if (countprod == 0) {
                JOptionPane.showMessageDialog(null, "No data found!.", "Alert", JOptionPane.WARNING_MESSAGE);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
        
        
        //DISPLAY DISABLED USERS.
        
        
        int usercount = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `users` WHERE `status`= 'disable' and `type`= 'user'");
            DefaultTableModel model = (DefaultTableModel) tabledisabledusers.getModel();
            int countdisableduser =0;
            while (datas.next()) {
                countdisableduser++;
                usercount= 1;
                model.addRow(new Object[]{datas.getInt("userId"),datas.getString("username"), datas.getString("email"), datas.getString("password")});
            }
            
            String calcdisableduser = String.valueOf(countdisableduser);
            calculatedisabledusers.setText(calcdisableduser );
          
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
        // DISPlAY DISABLED ADMIN
        
        
          int admincount = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `users` WHERE `status`= 'disable' and `type`= 'admin'");
            DefaultTableModel model = (DefaultTableModel) tabledisabledadmins.getModel();
            int countdisabledadmin =0;
            while (datas.next()) {
                countdisabledadmin++;
                admincount = 1;
                model.addRow(new Object[]{datas.getInt("userId"),datas.getString("username"), datas.getString("email"), datas.getString("password")});
            }
              String calcdisabledadmin = String.valueOf(countdisabledadmin);
             calculatedisabledadmin.setText(calcdisabledadmin );
            
            
           
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        
        
        //DISPLAY ARCHIVE PRODUCT
        
         int archivedcount = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `products` WHERE `status`='archive'");
            DefaultTableModel model = (DefaultTableModel) tablearchivedproducts.getModel();
            int countarchived =0;
            while (datas.next()) {
                countarchived++;
                archivedcount = 1;
                model.addRow(new Object[]{datas.getInt("productId"),datas.getString("productName"), datas.getString("productBrand"), datas.getInt("productPrice"), datas.getInt("productStocks"), datas.getString("productDescription")});
            }
             String calcproductarhived = String.valueOf( countarchived);
             calculateproductarchived.setText(calcproductarhived);
            
            if (count == 0) {
                JOptionPane.showMessageDialog(null, "No data found!.", "Alert", JOptionPane.WARNING_MESSAGE);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        
        
        
        ///COUNT ADMIN 
        
        
         /// DISPlAY ALL THE ADMIN
        
 
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `users` WHERE   `type`= 'admin'");
         
            int countadmin=0;
            while (datas.next()) {
                 countadmin++;
           
            }     
            String calcadmin = String.valueOf(countadmin);
             calculateadmin.setText(calcadmin);
           
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
        
        
        /// CALCULATE STOCKS
        
 
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `products`");
         
            int countstocks=0;
            while (datas.next()) {
                 countstocks+=datas.getInt("productStocks");
           
            }     
            String calcstocks = String.valueOf(countstocks);
             calculatestocks.setText(calcstocks);
           
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
            /// CALCULATE PRODUCTS
        
 
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `products`");
         
            int countproducts=0;
            while (datas.next()) {
                 countproducts++;
           
            }     
            String calcproducts = String.valueOf(countproducts);
             calculateproducts.setText(calcproducts);
           
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
        
        
         /// CALCULATE USERS
        
 
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
           ResultSet datas = stmt.executeQuery("select * from `users` WHERE   `type`= 'user'");
         
            int countusers=0;
            while (datas.next()) {
                 countusers++;
           
            }     
            String calcusers = String.valueOf(countusers);
             calculateuser.setText(calcusers);
           
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
        
        
      
         //DISPLAY ORDERED PRODUCTS
        
         int ordercount = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from orders ");
            DefaultTableModel model = (DefaultTableModel) tableorders.getModel();
            int countarchived =0;
            while (datas.next()) {
                countarchived++;
                ordercount = 1;
                model.addRow(new Object[]{datas.getInt("OrderId"),datas.getString("productName"), datas.getString("productBrand"), datas.getInt("productPrice"), datas.getString("productDescription"), datas.getInt("quantity"), datas.getInt("totalPrice"), datas.getString("status"), datas.getString("customer")});
            }
             String calcproductarhived = String.valueOf( countarchived);
             calculateorders.setText(calcproductarhived);
            
            if (count == 0) {
                JOptionPane.showMessageDialog(null, "No data found!.", "Alert", JOptionPane.WARNING_MESSAGE);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
        
        
           /// CALCULATE ORDERS
        
 
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
           ResultSet datas = stmt.executeQuery("select * from `orders`");
         
            int countorders=0;
            while (datas.next()) {
                 countorders++;
           
            }     
            String calcorders = String.valueOf(countorders);
             calculateorders.setText(calcorders);
           
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
        
        
           /// CALCULATE SALES
        
 
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javazigm1", "root", "");
            Statement stmt = con.createStatement();
            ResultSet datas = stmt.executeQuery("select * from `orders` WHERE   `status`= 'approved'");
         
            int totalsales=0;// THE SALES
          
            while (datas.next()) {
             
                totalsales+=datas.getInt("totalPrice");
             
           
            }     
           
           
             String calcsales = String.valueOf(totalsales);
             
             calculatesales.setText(calcsales);
           
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
        
        
        

    }
   
   
   
   
   
   
   
   


}
 

